name: Run Binance script

on:
  schedule:
    - cron: "0 3 * * *"  # Tous les jours à 03:00 UTC (23:00 à Montréal)
  workflow_dispatch:      # Permet de le lancer manuellement

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python main.py

    - name: Commit and push changes
      run: |
        git config user.name "Sydney"
        git config user.email "sydney@example.com"
        git pull origin main --rebase
        git add .
        git commit -m "auto: update CSVs from GitHub Actions" || echo "nothing to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
